POST http://localhost:3000/registration HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "test2",
    "name":"test Name"
}

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "test2"
   
}
###
GET http://localhost:3000/accounts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzQ5NDg0NSwiZXhwIjoxNjUzNDk4NDQ1fQ.N_7a9FHkUAaZ-Cqdepg0slxNDuBwuvK62Z3Kj5QRijg

###
POST http://localhost:3000/accounts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzQ5NDg0NSwiZXhwIjoxNjUzNDk4NDQ1fQ.N_7a9FHkUAaZ-Cqdepg0slxNDuBwuvK62Z3Kj5QRijg
Content-Type: application/json

{
    "groupId":2
}
###
GET  http://localhost:3000/bill/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzQ5NDg0NSwiZXhwIjoxNjUzNDk4NDQ1fQ.N_7a9FHkUAaZ-Cqdepg0slxNDuBwuvK62Z3Kj5QRijg

###
POST   http://localhost:3000/bill HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzQ5NDg0NSwiZXhwIjoxNjUzNDk4NDQ1fQ.N_7a9FHkUAaZ-Cqdepg0slxNDuBwuvK62Z3Kj5QRijg
Content-Type: application/json

{
    "groupId":2,
    "amount":20,
    "description":"Rented car"
}
###
GET  http://localhost:3000/groups HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1MzUwMjY0NSwiZXhwIjoxNjUzNTA2MjQ1fQ.BgpCJU5vJq_jwtzgZjHEHSQgKhV7Ya3IA3-dNcsjDBM

###